### ISSUE TITLE
Package Pulse Class into PyPi module 

### ISSUE THREAD

**Issue by akilhylton** [akilhylton/pulsetracker#2]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement the feature.
### Summary

Publish a PyPi module that will be updated each time the source code changes.

### Additional Context
Use this resource: https://packaging.python.org/tutorials/packaging-projects/

**Comment by ngiangre** [comment]
is this ready for the dist step? Would you say the master branch code is a solid version?

**Comment by akilhylton** [comment]
Yes it is a solid version that we can use as development platform.

**Comment by akilhylton** [comment]
https://pypi.org/project/pulsetracker/
